/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 love.glb 
*/

import React, { useRef ,useState} from 'react'
import { useGLTF } from '@react-three/drei'
import { MeshStandardMaterial } from 'three'

export default function Model(props) {
  const { nodes, materials } = useGLTF(`${process.env.PUBLIC_URL}/models/love.glb`)
  const [scale, setScale] = useState(2);
  const originalScale=useRef(4)
  const handleClick = () => {
    setScale(5); // 点击后设置缩放为 2
    setTimeout(() => {
      setScale(originalScale.current); // 1 秒后恢复原始缩放值
    }, 250);
  };
  return (
    
    <group {...props} dispose={null} scale={scale}>
      <mesh 
      geometry={nodes.texture_v100001.geometry} 
      material={new MeshStandardMaterial({ color: "rgb(223, 68, 68) "})}
      rotation={[Math.PI / 2, 0, 0]} 
      onClick={handleClick} // 添加点击事件
      />
      
    </group>
    
    
  )
}

useGLTF.preload(`${process.env.PUBLIC_URL}/models/love.glb`)
